"""empty message

Revision ID: 04bfad1b23c3
Revises: a7f46f74d691
Create Date: 2020-06-10 13:54:59.838954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04bfad1b23c3'
down_revision = 'a7f46f74d691'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hasPaid', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_user_hasPaid'), 'user', ['hasPaid'], unique=False)
    op.drop_column('user', 'xrefID')
    op.drop_column('user', 'refID')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('refID', sa.VARCHAR(length=64), nullable=True))
    op.add_column('user', sa.Column('xrefID', sa.VARCHAR(length=64), nullable=True))
    op.drop_index(op.f('ix_user_hasPaid'), table_name='user')
    op.drop_column('user', 'hasPaid')
    # ### end Alembic commands ###
