"""Removed refcode table cause only 1 code

Revision ID: 0965d2d474b6
Revises: de89aac14506
Create Date: 2020-05-24 11:44:10.372477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0965d2d474b6'
down_revision = 'de89aac14506'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_referalcode_referalID', table_name='referalcode')
    op.drop_table('referalcode')
    op.add_column('user', sa.Column('contactnum', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('fromrefID', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('torefID', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_contactnum'), 'user', ['contactnum'], unique=True)
    op.create_index(op.f('ix_user_fromrefID'), 'user', ['fromrefID'], unique=True)
    op.create_index(op.f('ix_user_torefID'), 'user', ['torefID'], unique=True)
    op.drop_index('ix_user_xrefID', table_name='user')
    op.drop_column('user', 'refID')
    op.drop_column('user', 'xrefID')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('xrefID', sa.VARCHAR(length=64), nullable=True))
    op.add_column('user', sa.Column('refID', sa.VARCHAR(length=64), nullable=True))
    op.create_index('ix_user_xrefID', 'user', ['xrefID'], unique=1)
    op.drop_index(op.f('ix_user_torefID'), table_name='user')
    op.drop_index(op.f('ix_user_fromrefID'), table_name='user')
    op.drop_index(op.f('ix_user_contactnum'), table_name='user')
    op.drop_column('user', 'torefID')
    op.drop_column('user', 'fromrefID')
    op.drop_column('user', 'contactnum')
    op.create_table('referalcode',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('referalID', sa.VARCHAR(length=64), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_referalcode_referalID', 'referalcode', ['referalID'], unique=1)
    # ### end Alembic commands ###
