"""Test int

Revision ID: 201ac01565db
Revises: defd2c7e7651
Create Date: 2020-06-16 20:13:13.791304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '201ac01565db'
down_revision = 'defd2c7e7651'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'xrefID')
    op.drop_column('user', 'refID')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('refID', sa.VARCHAR(length=64), nullable=True))
    op.add_column('user', sa.Column('xrefID', sa.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###
