"""Fixed refID issue

Revision ID: 227b1ad7e8c5
Revises: 5477a26ca2e1
Create Date: 2020-05-23 15:39:25.732708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '227b1ad7e8c5'
down_revision = '5477a26ca2e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'refID')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('refID', sa.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###
