"""referals

Revision ID: 263b0ec36aef
Revises: 04bfad1b23c3
Create Date: 2020-06-12 15:01:50.837922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '263b0ec36aef'
down_revision = '04bfad1b23c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('numberOfReferals', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_user_numberOfReferals'), 'user', ['numberOfReferals'], unique=False)
    op.drop_column('user', 'refID')
    op.drop_column('user', 'xrefID')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('xrefID', sa.VARCHAR(length=64), nullable=True))
    op.add_column('user', sa.Column('refID', sa.VARCHAR(length=64), nullable=True))
    op.drop_index(op.f('ix_user_numberOfReferals'), table_name='user')
    op.drop_column('user', 'numberOfReferals')
    # ### end Alembic commands ###
