"""Refral code typo fix

Revision ID: 5477a26ca2e1
Revises: 85d99c29bc92
Create Date: 2020-05-23 14:58:50.213857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5477a26ca2e1'
down_revision = '85d99c29bc92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'refID')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('refID', sa.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###
