"""Added isAdmin

Revision ID: b33a4de5561d
Revises: 263b0ec36aef
Create Date: 2020-06-12 19:19:52.820458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b33a4de5561d'
down_revision = '263b0ec36aef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('isAdmin', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_user_isAdmin'), 'user', ['isAdmin'], unique=False)
    op.drop_column('user', 'xrefID')
    op.drop_column('user', 'refID')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('refID', sa.VARCHAR(length=64), nullable=True))
    op.add_column('user', sa.Column('xrefID', sa.VARCHAR(length=64), nullable=True))
    op.drop_index(op.f('ix_user_isAdmin'), table_name='user')
    op.drop_column('user', 'isAdmin')
    # ### end Alembic commands ###
