"""Names are no longer unique keys

Revision ID: de89aac14506
Revises: 227b1ad7e8c5
Create Date: 2020-05-23 20:58:54.183637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de89aac14506'
down_revision = '227b1ad7e8c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_firstname', table_name='user')
    op.create_index(op.f('ix_user_firstname'), 'user', ['firstname'], unique=False)
    op.drop_index('ix_user_lastname', table_name='user')
    op.create_index(op.f('ix_user_lastname'), 'user', ['lastname'], unique=False)
    op.drop_column('user', 'refID')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('refID', sa.VARCHAR(length=64), nullable=True))
    op.drop_index(op.f('ix_user_lastname'), table_name='user')
    op.create_index('ix_user_lastname', 'user', ['lastname'], unique=1)
    op.drop_index(op.f('ix_user_firstname'), table_name='user')
    op.create_index('ix_user_firstname', 'user', ['firstname'], unique=1)
    # ### end Alembic commands ###
