"""Fixed casing and issues

Revision ID: e8349d0dd285
Revises: f73c3ee772ea
Create Date: 2020-05-23 13:37:49.428325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8349d0dd285'
down_revision = 'f73c3ee772ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('refID', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refid_refID'), 'refid', ['refID'], unique=True)
    op.drop_index('ix_refID_refID', table_name='refID')
    op.drop_table('refID')
    op.add_column('user', sa.Column('lastname', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_lastname'), 'user', ['lastname'], unique=True)
    op.drop_column('user', 'refID')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('refID', sa.VARCHAR(length=64), nullable=True))
    op.drop_index(op.f('ix_user_lastname'), table_name='user')
    op.drop_column('user', 'lastname')
    op.create_table('refID',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('refID', sa.VARCHAR(length=64), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_refID_refID', 'refID', ['refID'], unique=1)
    op.drop_index(op.f('ix_refid_refID'), table_name='refid')
    op.drop_table('refid')
    # ### end Alembic commands ###
