"""Added paydetails

Revision ID: f3d520f70503
Revises: b33a4de5561d
Create Date: 2020-06-13 21:05:07.924182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3d520f70503'
down_revision = 'b33a4de5561d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('bname', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('ifsc', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('paynum', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_bname'), 'user', ['bname'], unique=False)
    op.create_index(op.f('ix_user_ifsc'), 'user', ['ifsc'], unique=False)
    op.create_index(op.f('ix_user_paynum'), 'user', ['paynum'], unique=False)
    op.drop_column('user', 'refID')
    op.drop_column('user', 'xrefID')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('xrefID', sa.VARCHAR(length=64), nullable=True))
    op.add_column('user', sa.Column('refID', sa.VARCHAR(length=64), nullable=True))
    op.drop_index(op.f('ix_user_paynum'), table_name='user')
    op.drop_index(op.f('ix_user_ifsc'), table_name='user')
    op.drop_index(op.f('ix_user_bname'), table_name='user')
    op.drop_column('user', 'paynum')
    op.drop_column('user', 'ifsc')
    op.drop_column('user', 'bname')
    # ### end Alembic commands ###
