"""Added refID model with relation

Revision ID: f73c3ee772ea
Revises: 51746121e9d4
Create Date: 2020-05-22 01:21:31.061182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f73c3ee772ea'
down_revision = '51746121e9d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refID',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('refID', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refID_refID'), 'refID', ['refID'], unique=True)
    op.add_column('user', sa.Column('xrefID', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_xrefID'), 'user', ['xrefID'], unique=True)
    op.drop_index('ix_user_refID', table_name='user')
    op.drop_column('user', 'refID')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('refID', sa.VARCHAR(length=64), nullable=True))
    op.create_index('ix_user_refID', 'user', ['refID'], unique=1)
    op.drop_index(op.f('ix_user_xrefID'), table_name='user')
    op.drop_column('user', 'xrefID')
    op.drop_index(op.f('ix_refID_refID'), table_name='refID')
    op.drop_table('refID')
    # ### end Alembic commands ###
